### ISSUE TITLE
Grid is Null when use Grid in @Beforexxx

### ISSUE THREAD

**Issue by sgyyz** [paypal/SeLion#156]
As I see the SeleniumGridListener, there is a method to check the invoked method is test method or not, but I think there are something missing. When we use the currently session or create a new session in the @BeforeXXX methods, it won't create a new session.

This situation will be used for some common actions before the test case method.

Hope it will be fixed later.

**Comment by mach6** [comment]
@sgyyz 

By design, we do not support session manipulation in `@BeforeXXX` or `@AfterXXX` for non-session shared tests (the typical use case).

This said, there is an open ask/bug to add support (access to a non-null Grid object) for `@BeforeClass` and `@AfterClass` when session sharing (http://paypal.github.io/SeLion/html/documentation.html#webdriver-sessions-sharing) is used -- which I am looking into.

**Comment by sgyyz** [comment]
@mach6 
This is one of the solution, I think some time we should extract these operations in to the abstract class, and then the sub class will extend from the super class. so we should use the `@BeforeClass` and `@AfterClass`. The common operation such as login before these, logout after logout. Also maybe suite for `@BeforeMethod`, `@AfterMethod` and the other annotation in TestNG.

I think that if can add these features in it will be perfect.
