### ISSUE TITLE
Enhancing SeLion-Grid to be compatible with heterogenous environment

### ISSUE THREAD

**Issue by ysecaran** [paypal/SeLion#36]
Right now a user can host a Grid and node "only" on the same platform. If the grid is on linux then all nodes must be on linux. same goes for windows and mac. This should be enhanced to multiple platforms where a user can hook up linux/mac/windows node to a grid irrespective of platforms.

**Comment by mach6** [comment]
@ysecaran Is this issue still valid? I currently have a Win hub with a Win node and a Linux node plumbed together with SeLion-Grid... Furthermore, I'm able to route to a specific node through the hub via `DesiredCapabilities`

![image](https://cloud.githubusercontent.com/assets/3238999/6313065/cf4aa166-b94d-11e4-947a-0c2db211fd55.png)

**Comment by ysecaran** [comment]
@mach6 the issue comes when the user tries to do a auto upgrade. Right now, the UI page rendered for auto upgrade is based upon the platform on which the grid is hosted. I hosted a linux grid with a linux node and mac node. 

![screen shot 2015-02-23 at 12 01 36 pm](https://cloud.githubusercontent.com/assets/8719446/6323598/24907450-bb53-11e4-8621-a1dfa73cc040.png)

The grid still shows UI page(as above) for upgrading nodes on linux platform while the rest of the nodes will become unstable after the upgrade.

**Comment by krmahadevan** [comment]
@mach6 
Is this a priority problem right now ? I believe that we would need to revisit our auto upgrade logic and all the entire functionalities associated with it because if you look at it.. it was originally built to support just our Grid farm.. We would need to revisit the logic such that it now does the following 
- Accept the URLs for all platform specific binaries in the UI and then this information is relayed to the relevant nodes based on their PLATFORM as capabilities 
- If the Grid farm contains a flavor for which there wasn't no input provided then it would need to inform the user while the user is still at the upgrade screen.

But I am of the opinion that for now this can take the back bench and we can focus on the other important things that are still on the road map.

**Comment by mach6** [comment]
This is addressed with this commit https://github.com/paypal/SeLion/commit/08b90ec46df420e843e4dce617d6415d15e9a0bf
